service: videolyzer # NOTE: update this with your service name


provider:
  name: aws
  runtime: python3.7
  profile: ${file(../config.${self:provider.stage}.json):videolyzer.profile}
  region: ${file(../config.${self:provider.stage}.json):videolyzer.region}


functions:
  startProcessingVideo:
    handler: handler.start_processing_video
    events:
      - s3:
          bucket: ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4
